#!/bin/bash

DATE=$(date +%d-%m-%y)
BACKUP_SUFFIX=backup_$DATE
DIR=$(pwd)

# Backup current files
mv ~/.bashrc ~/.bashrc_$BACKUP_SUFFIX
mv ~/.tmux.conf ~/.tmux.conf_$BACKUP_SUFFIX
mv ~/.vimrc ~/.vimrc_$BACKUP_SUFFIX

# Create symlinks
ln $DIR/.bashrc ~/.bashrc
ln $DIR/.tmux.conf ~/.tmux.conf
ln $DIR/.vimrc ~/.vimrc

echo "Diretorio $DIR"

source ~/.bashrc
